### ISSUE TITLE
Fix that

### ISSUE THREAD

**Issue by pascalau** [duckietown/apriltags3-py#3]
@AleksandarPetrov 

https://github.com/duckietown/apriltags3-py/blob/e4e7787659513109fd766f693b83d38442e737ee/apriltags3.py#L435

**Comment by surirohit** [comment]
Yes master!

**Comment by surirohit** [comment]
Fixed in https://github.com/duckietown/apriltags3-py/commit/f6f19e4fd03cbc4b9b370a71a3b67947a166ee1d
